services:
  cryptopro:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: onessa

    # сюда подтянутся все LDAP_* и прочие переменные
    env_file:
      - .env

    volumes:
      # директория с данными (в контейнере /data, см. DATA_DIR по умолчанию)
      - ./data:/data

    ports:
      - "8080:8080"

    restart: unless-stopped
